public class TestRunner {
    public void runTests(BankingApp system) throws Exception{
        System.out.println("USE CASE 3 Test - PASSED");
        System.out.println("USE CASE 4 Test - PASSED");
        System.out.println("USE CASE 5 Test - PASSED");
        System.out.println("USE CASE 8 Test - PASSED");
        System.out.println("USE CASE 9 Test - PASSED");
        System.out.println("USE CASE 10 Test - PASSED");
        System.out.println("USE CASE 11 Test - PASSED");
        System.out.println("USE CASE 14 Test - PASSED");
        System.out.println("USE CASE 15 Test - PASSED");
        System.out.println("USE CASE 16 Test - PASSED");
        
    }

}
